Fix a bug that somwtimes colorize option doesn't work
If colorize option was declared like this:

    Rack::SpyUp.config do |config|
      config.colorize = false
    end

Then it'll just blow up and you'll get:

    NoMethodError:
      undefined method `colorize=' for #<Rack::SpyUp::Configuration:0x00000000ff15e0>

This commit fixes this bug and now this can be configured even on Rails.